#################################
# Trigger = github action
# executeion happens on the github side
# backend = terraform cloud (TF Cloud is state file only - no config or additional needed)
# TF Cloud Workspace - single workspace per state file - means every sport/env combo requires a new workspace
#################################
name: 'Streamlit GCP AppEngine Deployment'

on:
  push:
    #paths:
    #- 'basketball-nba/**'                     #config-here
    branches:
    - main
    - dev
  #pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

#env:
#  sport: basketball-nba                      #config-here

##################################################################################################
# No changes below here
##################################################################################################
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: GCP Setup
      uses: google-github-actions/setup-gcloud@v0
      with:
        version: '290.0.1'
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_key: ${{ secrets.GOOGLE_CREDENTIALS }}
        export_default_credentials: true
    - id: Deploy
      uses: google-github-actions/deploy-appengine@main
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        credentials: ${{ secrets.GOOGLE_CREDENTIALS }}
        deliverables: server/app.yml

    - name: 'show output'
      run: 'echo ${{ steps.deploy.outputs.url }}'
